language: r
warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change

r_apt_packages:
  - testthat
  - knitr
  - dplyr

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
